# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import msg_pb2 as msg__pb2


class MsgServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMsg = channel.unary_unary(
        '/MsgService/GetMsg',
        request_serializer=msg__pb2.MsgRequest.SerializeToString,
        response_deserializer=msg__pb2.MsgResponse.FromString,
        )


class MsgServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMsg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MsgServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMsg': grpc.unary_unary_rpc_method_handler(
          servicer.GetMsg,
          request_deserializer=msg__pb2.MsgRequest.FromString,
          response_serializer=msg__pb2.MsgResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MsgService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
